GAG/GAG/Models/BaseModel.cs
namespace GAG.Models
{
    public class BaseModel
    {
        public string ukPrnNo { get; set; }
    }
}

GAG/GAG/Models/Gag/CalculationDetailsModel.cs
using System.Collections.Generic;
using GAG.Core.Domain.Gag;

namespace GAG.Models.Gag
{
    public class CalculationDetailsModel
    {
        public Period Period { get; set; }

        public Provider Provider { get; set; }

        public FundingStream FundingStream { get; set; }

        public List<PolicyResult> PolicyResults { get; set; }
    }
}

GAG/GAG/Models/Gag/GagSummaryModel.cs
using GAG.Core.Domain.Gag;

namespace GAG.Models.Gag
{
    public class GagSummaryModel : BaseModel
    {
        public ProviderResultSummary GagStatementSummary { get; set; }

        public SchoolFundingModel SchoolFundingModel { get; set; }
    }
}

GAG/GAG/Models/Gag/SchoolBudgetShareModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GAG.Models.Gag
{
    public class SchoolBudgetShareModel : BaseModel
    {
        public int KeyStage1Pupils { get; set; }
        public decimal KeyStage1Rate { get; set; }
        public decimal KeyStage1Total { get; set; }

        public int KeyStage2Pupils { get; set; }
        public decimal KeyStage2Rate { get; set; }
        public decimal KeyStage2Total { get; set; }

        public int KeyStage3Pupils { get; set; }
        public decimal KeyStage3Rate { get; set; }
        public decimal KeyStage3Total { get; set; }

        public int KeyStage4Pupils { get; set; }
        public decimal KeyStage4Rate { get; set; }
        public decimal KeyStage4Total { get; set; }

        public int DeprivationSecondaryIdaciFPupils { get; set; }
        public decimal DeprivationSecondaryIdaciFRate { get; set; }
        public decimal DeprivationSecondaryIdaciFTotal { get; set; }

        public int DeprivationSecondaryIdaciEPupils { get; set; }
        public decimal DeprivationSecondaryIdaciERate { get; set; }
        public decimal DeprivationSecondaryIdaciETotal { get; set; }

        public int DeprivationSecondaryIdaciDPupils { get; set; }
        public decimal DeprivationSecondaryIdaciDRate { get; set; }
        public decimal DeprivationSecondaryIdaciDTotal { get; set; }

        public int DeprivationSecondaryFsmPupils { get; set; }
        public decimal DeprivationSecondaryFsmRate { get; set; }
        public decimal DeprivationSecondaryFsmTotal { get; set; }

        public int EngishAddSecondaryEalPupils { get; set; }
        public decimal EngishAddSecondaryEalRate { get; set; }
        public decimal EngishAddSecondaryEalTotal { get; set; }

        public int SecondaryLumpSumPupils { get; set; }
        public decimal SecondaryLumpSumRate { get; set; }
        public decimal SecondaryLumpSumTotal { get; set; }

        public decimal TotalPupilLedfactors { get; set; }
        public decimal TotalOtherFactors { get; set; }
        public decimal TotalSchoolBudgetShare { get; set; }
    }
}

GAG/GAG/Models/Gag/SchoolFundingModel.cs
using System.Collections.Generic;
using GAG.Core.Domain.Gag;

namespace GAG.Models.Gag
{
    public class SchoolFundingModel : BaseModel
    {
        public List<FundingStreamResults> Allocations { get; set; }
    }
}

GAG/GAG/Controllers/GagController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using GAG.Core.Domain.Gag;
using GAG.Core.Services.Gag;
using GAG.Models.Gag;

namespace GAG.Controllers
{
    public class GagController : Controller
    {
        private readonly IGagService _gagService;

        public GagController(IGagService gagService)
        {
            _gagService = gagService;
        }

        public ActionResult Summary()
        {
            string ukPrn = "10033799";

            var gagStatment = _gagService.GenerateGagStatement(ukPrn, new DateTime());
            
            var model = new GagSummaryModel
            {
                GagStatementSummary = gagStatment,
                SchoolFundingModel = new SchoolFundingModel
                {
                    Allocations = gagStatment.FundingStreamResults
                },
                ukPrnNo = ukPrn
            };

            model.GagStatementSummary.Period.StartDate =
                DateTime.Parse(model.GagStatementSummary.Period.StartDate).Year.ToString();
            model.GagStatementSummary.Period.EndDate =
                DateTime.Parse(model.GagStatementSummary.Period.EndDate).Year.ToString();

            return View(model);
        }

        // Replace fundingStreamCode with 
        public ActionResult Details(string ukPrn, Period period, string fundingStream)
        {
            ukPrn = "10033799";
            period.PeriodId = "2017181";
            fundingStream = "YPLRE";

            var detail = _gagService.GetCalculations(ukPrn, period, fundingStream);

            var model = new CalculationDetailsModel
            {
                Period = detail.Period,
                Provider = detail.Provider,
                FundingStream = detail.FundingStream
            };

            return View(model);
        }
    }
}

GAG/GAG/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GAG.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

GAG/GAG/Views/Gag/Details.cshtml
@model GAG.Models.Gag.CalculationDetailsModel
@{
    Layout = "~/Views/Shared/_oneColumn.cshtml";
}

GAG/GAG/Views/Gag/SchoolBudgetShare.cshtml
@model GAG.Models.Gag
@{
    Layout = "~/Views/Shared/_twoColumn.cshtml";
}

GAG/GAG/Views/Gag/Summary.cshtml
@model GAG.Models.Gag.GagSummaryModel
@{
    Layout = "~/Views/Shared/_twoColumn.cshtml";
}

<div class="grid-row">
    <div class="column-two-thirds">
        <h1 class="heading-secondary">@Model.GagStatementSummary.Provider.LegalName</h1>
        <p>UKPRN: @Model.GagStatementSummary.Provider.UkPrn</p>
        <h1 class="heading-large margin-bottom">Funding for @Model.GagStatementSummary.Period.StartDate to @Model.GagStatementSummary.Period.EndDate </h1>
        <h3 class="bold-medium">School Funding</h3>

        <p></p>

        @Html.Partial("_SchoolFunding", Model.SchoolFundingModel)

        <div id="wrapper">
            <main class="group" id="content" role="main">
                <section>


                    <table class="table-collapsible floated-header">

                        <thead>
                        <tr>
                            <th class="bold-medium" role="columnheader" scope="col" data-key="department_name">
                                <a class="bold-medium">Total Allocation </a>
                            </th>



                            <th style="text-align: right;" aria-sort="descending" scope="col" data-key="number_of_transactions"><a class="bold-medium" role="button">@Model.GagStatementSummary.FundingStreamResults[0].TotalAmount.ToString("0.##") </a></th>
                        </tr>
                        </thead>

                    </table>


                </section>


            </main>
        </div>
    </div>

    <div class="related-container">
        <aside class="related" id="related">
            <div class="inner group related-subsection">
                <h2 id="parent-subsection">General Annual Grant</h2>
                <nav role="navigation" aria-labelledby="parent-subsection">
                    <ul>
                        <li>
                            <a href="history">Download your statements</a>
                        </li>




                    </ul>
                </nav>
            </div>
            <br>
            <div class="inner group related-subsection">
                <h2 id="parent-subsection">ESFA Funding</h2>
                <nav role="navigation" aria-labelledby="parent-subsection">
                    <ul>
                        <li>
                            <a href="https://www.gov.uk/government/publications/pupil-premium-conditions-of-grant-2017-to-2018">National Non Domestic Rates</a>
                        </li>
                        <li>
                            <a href="https://www.gov.uk/government/publications/year-7-catch-up-premium-2016-to-2017-allocations">PE and Sport Premium for Primary Schools</a>
                        </li>
                        <li>
                            <a href="https://www.gov.uk/government/publications/pupil-premium-conditions-of-grant-2017-to-2018">Pupil Premium</a>
                        </li>
                        <li>
                            <a href="https://www.gov.uk/government/publications/year-7-catch-up-premium-2016-to-2017-allocations">Universal Infant Free School Meals</a>
                        </li>

                    </ul>
                </nav>
            </div>


            <br>


            <div>
                <h2 id="parent-subsection">Local Authority Funding</h2>
                <nav role="navigation" aria-labelledby="parent-subsection">
                    <ul>
                        <li>
                            <a href="#">Early Years</a>
                        </li>
                        <li>
                            <a href="#">High Needs Top Up</a>
                        </li>




                    </ul>
                </nav>
            </div>
        </aside>


    </div>
</div>

GAG/GAG/Views/Gag/_SchoolFunding.cshtml
@model GAG.Models.Gag.SchoolFundingModel

<div id="wrapper">
    <main class="group" id="content" role="main">
        <section class="filtered-list visualisation-table" id="filtered-list">


            <table class="table-collapsible floated-header">

                <thead>
                    <tr>
                        <th width="700" class="sentence" role="columnheader" scope="col" data-key="department_name">
                            <a class="js-sort" role="button">Description</a>
                        </th>

                        <th>Total</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var allocation in Model.Allocations[0].Allocations)
                    {
                        <tr>
                            <td>@allocation.AllocationLine.AllocationLineName</td>
                            <td class="table-figures">@allocation.AllocationAmount.ToString("0.##")</td>
                        </tr>
                    }
                </tbody>
            </table>
        </section>

    </main>
</div>

GAG/GAG/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

GAG/GAG/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

GAG/GAG/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="">
    Click @Html.ActionLink("here", "Summary", "Gag", null, new { @class = "page-scroll" }) to go to the summary page
</div>

GAG/GAG/Views/Shared/_Layout.cshtml
@{ Layout = null; }
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css/govuk-template.css")
    @Styles.Render("~/Content/css/site.css")
    @Styles.Render("~/Content/css/application.css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Content/css/fonts.css")
</head>
<body>
   @Html.Partial("~/Views/Shared/_header.cshtml");
    <div class="container body-content" id="main">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

GAG/GAG/Views/Shared/_header.cshtml
<header role="banner" id="global-header" class="with-proposition">
    <div class="header-wrapper">
        <div class="header-global">
            <div class="header-logo">
                <a href="https://www.gov.uk" title="Go to the GOV.UK homepage" id="logo" class="content">
                    <img src="~/Content/images/gov.uk_logotype_crown_invert_trans.png?0.19.2" width="36" height="32" alt=""> GOV.UK
                </a>
            </div>
        </div>
        <div class="header-proposition">
            <div class="content">
                <a href="#proposition-links" class="js-header-toggle menu">Menu</a>
                <nav id="proposition-menu">
                    <a href="/" id="proposition-name">
                        Manage your education and skills funding
                    </a>
                </nav>
            </div>
        </div>
    </div>
</header>
<div id="global-header-bar"></div>

GAG/GAG/Views/Shared/_oneColumn.cshtml
@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 

<div>
    @RenderBody()
</div>

GAG/GAG/Views/Shared/_twoColumn.cshtml
@{
    ViewBag.Title = "title";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
 

<div>
    @RenderBody()
</div>
<div>
    @RenderSection("OneThird", required: false)
</div>